### Social Media APIs
@base_url = http://localhost:8000
@post_id = 1

# Posts endpoints
### Create post
POST {{base_url}}/posts
Content-Type: application/json

{
  "body": "This is a post."
}

### Get list of posts
GET {{base_url}}/posts

### Get comments on post
GET {{base_url}}/posts/{{post_id}}/comments

### Get post with comments
GET {{base_url}}/posts/{{post_id}}


# Comments endpoints
### Create comment
POST {{base_url}}/comments
Content-Type: application/json

{
  "body": "This is a comment.",
  "post_id": {{post_id}}
}