vars: {
  d2-config: {
    pad: 5 # keeps 5px-ish padding around the graph
  }
}

**.style.border-radius: 5

shape: sequence_diagram
client -> server: send request\nGET /post?sorting=new
server -> client: return\nresponse
